# Configuration

config:
  # MD013 - line-length

  line_length:
    line_length: 120
    code_blocks: false
    tables: false
  html:
    allowed_elements:
      - div

# Globs

globs:
  - "**/*.md"
  - "*.md"

# Ignores

ignores:
  - "_site/**/*.qmd"

# Fix any fixable errors

fix: true
